### ISSUE TITLE
Compatibility terraform 12

### ISSUE THREAD

**Issue by nysthee** [francescop/kafka_schema_registry_terraform_provider#1]
Hi 

Are there any plans to make this provider terraform 12 compatible?

Thanks

**Comment by francescop** [comment]
Hello Thomas,
I will check better next weekend, but it should still work.

Did you already try to run it on terraform 0.12 ?

**Comment by nysthee** [comment]
Hi Francesco

Thanks for your response. We indeed already tried it and we get the following output when planning.


running "/atlantis-data/bin/terraform0.12.6 plan -input=false -refresh -no-color -out \"/atlantis-data/repos/Data_Analytics/di-infrastructure/72/default/ef-di-dap/ef-di-dap-default.tfplan\"" in "/atlantis-data/repos/Data_Analytics/di-infrastructure/72/default/ef-di-dap": exit status 1

Error: Failed to instantiate provider "schemaregistry" to obtain schema: fork/exec /home/atlantis/.terraform.d/plugins/linux_amd64/terraform-provider-schemaregistry: exec format error



- - -
Thomas

On 15 September 2019 at 16:32:36, francesco palazzini (notifications@github.com) wrote:

Hello Thomas,
I will check better next weekend, but it should still work.

Did you already try to run it on terraform 0.12 ?

**Comment by jinbowang** [comment]
Chiming in here, I encountered exactly the same issue:

`terraform init -v`
`Terraform v0.12.6`
`+ provider.datadog v2.4.0`
`+ provider.google v1.16.1`
`+ provider.schemaregistry (unversioned)`

`Your version of Terraform is out of date! The latest version
is 0.12.9. You can update by downloading from www.terraform.io/downloads.html`

and when trying terraform plan: 
`Error: Failed to instantiate provider "schemaregistry" to obtain schema: fork/exec /Users/jwang/.terraform/plugins/darwin_amd64/terraform-provider-schemaregistry: exec format error`

**Comment by francescop** [comment]
Hello @nysthee and @jinbowang ,
I did recompile the binaries. 
please check [this](https://github.com/francescop/kafka_schema_registry_terraform_provider/releases/tag/v1.0.0).

else you can compile it by yourself.

let me know how it goes.

**Comment by jinbowang** [comment]
> Hello @nysthee and @jinbowang ,
> I did recompile the binaries.
> please check [this](https://github.com/francescop/kafka_schema_registry_terraform_provider/releases/tag/v1.0.0).
> 
> else you can compile it by yourself.
> 
> let me know how it goes.

I tried to build it myself and the one you compiled, and I am still getting the same error

**Comment by francescop** [comment]
@jinbowang how did you compile it?

this is my setup:
```
$ go version
go version go1.12.7 linux/amd64
$ terraform version
Terraform v0.12.0

Your version of Terraform is out of date! The latest version
is 0.12.9. You can update by downloading from www.terraform.io/downloads.html
$ uname -a
Linux fp-t470s 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

please try:
```
export GO111MODULE=auto
make test
```

**Comment by francescop** [comment]
Closing for now.
If the problem persists please reopen it.
Thanks.
